
server:
    port: 8084
    servlet:
        context-path: /api/oauth

springfox:
    documentation:
        swagger:
            v2:
                path: /api-docs

spring:
    application:
        name: oauthorization
    data:
        mongodb:
            uri: mongodb://usersecurity.sandbox.limbo.work:27027/authorization
    redis:
        host: localhost
        port: 6379
#        timeout: 60000
    cache:
        type: REDIS
        redis:
            cache-null-values: false
            use-key-prefix: true
            key-prefix: auth
            time-to-live: 60000

picpay:
    service:
        auth:
            jwt:
                secret: "%C*F-J@NcRfUjXn2r5u8x/A?D(G+KbPd"


logging:
    pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %highlight(%-5level) %magenta([%t]) %m%n"
    level:
        org:
            springframework:
                data:
                    mongodb:
                        core:
                            MongoTemplate: DEBUG